### ISSUE TITLE
Cannot Generate Flatworld

### ISSUE THREAD

**Issue by krischej** [Berserker66/omnitool#22]
Upon attempting to generate a flatworld via the plugin, I get the following traceback in the console window:

Process Flatworld:
Traceback (most recent call last):
  File "C:\Python34 64Bit\lib\multiprocessing\process.py", line 254, in _bootstrap
  File "C:\Python34 64Bit\lib\multiprocessing\process.py", line 93, in run
  File "E:\Dropbox\PyTerraria\omnitool\relay.py", line 7, in run_flat
  File "E:\Dropbox\PyTerraria\omnitool\relay.py", line 27, in launch_plugin
  File "E:\Dropbox\PyTerraria\omnitool__init__.py", line 873, in launch_plugin
  File "E:\Dropbox\PyTerraria\omnitool\plugins\flatworld.py", line 15, in **init**
  File "E:\Dropbox\PyTerraria\omnitool\plugins\flatworld.py", line 118, in gen_gui
AttributeError: 'list' object has no attribute 'value'

Terraria Version: 1.3.0.8
Omnitool Version: 18.2.1
on Win10 x64

**Comment by krischej** [comment]
Thanks for the quick fix Berserker!

**Comment by Berserker66** [comment]
No Problem
